# Exercises

### #1 - Calculate the BMI (body mass index) on the two lists below using NDArrays...

In [1]:
import numpy as np
# formula = weight / (height**2) * 730
height = [69, 70, 71, 72, 73, 74, 75]
weight = [110, 120, 130, 140, 150, 160, 170]
height_array=np.array(height)
weight_array=np.array(weight)
bmi=weight_array/(height_array**2)*730
bmi


array([16.86620458, 17.87755102, 18.82562984, 19.71450617, 20.54794521,
       21.32943755, 22.06222222])

### #2 - Create a function that will take in two parameters and will create a random matrix based off of those parameters. Extra: Have additional parameters taken in that allow the user to choose the shape and data type of the matrix.

In [5]:

def random_matrix(rows,cols,shape=None, dtype=float):
    if shape:
        matrix_shape=shape
    else:
        matrix_shape=(rows,cols)
    random_matrix=np.random.rand(*matrix_shape).astype(dtype)
    return random_matrix
matrix=random_matrix(6,7,dtype=int)
print(matrix)

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]


### #3 - Extra: Open and load the data in the two text files that have the Boston Red Sox hitting data for the past seasons. Compare the difference in the two years by putting the data into an NDArray and running a differencial operation on it. The column to look for will be SLG.

Your output should display which year (either 2017 or 2018) was a better year based on SLG

In [9]:
import numpy as np

def load_data(file_path):
    return np.genfromtxt(file_path, delimiter=',', dtype=None, encoding=None, names=True)

def compare_slg(file_2017, file_2018):
   
    data_2017 = load_data(file_2017)
    data_2018 = load_data(file_2018)

 
    slg_2017 = data_2017['SLG']
    slg_2018 = data_2018['SLG']


    mean_slg_2017 = np.mean(slg_2017)
    mean_slg_2018 = np.mean(slg_2018)

    
    if mean_slg_2018 > mean_slg_2017:
        return f"2018 was a better year based on SLG with an average SLG of {mean_slg_2018:.3f} compared to {mean_slg_2017:.3f} in 2017."
    else:
        return f"2017 was a better year based on SLG with an average SLG of {mean_slg_2017:.3f} compared to {mean_slg_2018:.3f} in 2018."


file_2017 = r"C:\Users\Zaur\OneDrive\Desktop\Disk\2023Nazrin\Bootcamp_coding temple\Python Advanced\Python advanced_task\Numpy\redsox_2017.txt"
file_2018 = r"C:\Users\Zaur\OneDrive\Desktop\Disk\2023Nazrin\Bootcamp_coding temple\Python Advanced\Python advanced_task\Numpy\redsox_2018.txt"


result = compare_slg(file_2017, file_2018)
print(result)



2017 was a better year based on SLG with an average SLG of 0.393 compared to 0.388 in 2018.


In [16]:
import numpy as np
FIELDS = ['Rk', 'Pos', 'Name', 'Age', 'G', 'PA', 'AB', 'R', 'H', '2B', '3B', 'HR', 'RBI', 'SB', 'CS', 
          'BB', 'SO', 'BA', 'OBP', 'SLG', 'OPS', 'OPS+', 'TB', 'GDP', 'HBP', 'SH', 'SF', 'IBB']

DATATYPES = [('rk', 'i'), ('pos', '|S25'), ('name', '|S25'), ('age', 'i'), ('g', 'i'), ('pa', 'i'), ('ab', 'i'),
                ('r', 'i'), ('h', 'i'), ('2b', 'i'), ('3b', 'i'), ('hr', 'i'), ('rbi', 'i'), ('sb', 'i'), ('cs', 'i'),
                ('bb', 'i'), ('so', 'i'), ('ba', 'f'), ('obp', 'f'), ('slg', 'f'), ('ops', 'f'), ('opsp', 'i'),
                ('tb', 'i'), ('gdp', 'i'), ('hbp', 'i'), ('sh', 'i'), ('sf', 'i'), ('ibb', 'i')]

#Use this function to actually open the data inside of a NDArray
filename = r"C:\Users\Zaur\OneDrive\Desktop\sample.csv"
data = np.genfromtxt(filename, delimiter=',', dtype=DATATYPES, names=FIELDS, skip_header=1)


print(data['Name'])



[]


C:\Users\Zaur\AppData\Local\Temp\ipykernel_10216\3123350519.py:12: UserWarning: genfromtxt: Empty input file: "C:\Users\Zaur\OneDrive\Desktop\sample.csv"
  data = np.genfromtxt(filename, delimiter=',', dtype=DATATYPES, names=FIELDS, skip_header=1)
